### PR TITLE
Add contrast

### PR DESCRIPTION
**Pull request by tmorton**
I think this is a great project. This PR has some significant changes, but hopefully keeps the spirit intact.  Consider it the start of a discussion, not something to be merged in as-is.
# Language Changes

I've put all of the points in the format `We value X over Y`  I think "we" is better than "I", because this is about community, not personal virtue.  

Values mean nothing without tradeoffs.  This manifesto outlines things we value - but it should outline our _most important_ values as a programming community.  So we include the right-hand things, which are also good things, but less valuable.  When forced to choose between them, we should favor the left-hand things.  

These are not absolutes.  Sometimes you need to make the opposite tradeoff.  But what makes the "happiness-driven" community different is that we will favor the left-hand values whenever possible.
# Implications

Language aside, I've made some substantive changes to the manifesto.  For example, I think the community should favor open-source over corporate solutions - yes, this includes Apple's App Store.  Not that iOS development is unwelcome - tradeoffs and all that - but where possible, we should push for openness.

### CODE REVIEW

**Comment by jlucasps** [comment]
:+1:

**Comment by scottefein** [comment]
I'm going to try and bring this in point by point... will add individual commits here and then we can comment on those-trying to merge this all in one is confusing me haha.

**Comment by scottefein** [comment]
OK, went point by point with this an updated... @tmorton let me know what you think. I took most of what you had and just reworked with what had changed in the mean time.

**Comment by tmorton** [comment]
I like the new version - definitely some improvements over my last version ("clarity over cleverness" is great).

**Comment by scottefein** [comment]
Great! Thanks for this-Closing this one, open up a new one if you have any other ideas

**Pull request closed without merging**
